// <auto-generated />
using System;
using CustomerShoppingApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomerShoppingApp.Migrations
{
    [DbContext(typeof(CustomerShoppingCartContext))]
    partial class CustomerShoppingCartContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustomerShoppingApp.Models.Address", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("houseNumber")
                        .HasColumnType("int");

                    b.Property<string>("postCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.BankDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("accountNumber")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("bankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expiryDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sortCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("BankDetails");
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.Cloth", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("brand")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("clothType")
                        .HasColumnType("varchar(20)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<float>("size")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Cloth");
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("age")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<string>("email")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("firstName")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.HasKey("id");

                    b.ToTable("Customer", "Users");
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.Furniture", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("furnitureName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("material")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Furniture");
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.Garden", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("plantName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(5,2)");

                    b.Property<float>("weight")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Garden");
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ShoppingCartId")
                        .IsUnique();

                    b.ToTable("Item");
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.Shoe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("brand")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(5,2)");

                    b.Property<float>("size")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Shoe");
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.ShoppingCart", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("shoppingCartName")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.HasKey("id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("ShoppingCart", "Basket");
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.Address", b =>
                {
                    b.HasOne("CustomerShoppingApp.Models.Customer", null)
                        .WithOne("address")
                        .HasForeignKey("CustomerShoppingApp.Models.Address", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.BankDetail", b =>
                {
                    b.HasOne("CustomerShoppingApp.Models.Customer", null)
                        .WithOne("bankDetail")
                        .HasForeignKey("CustomerShoppingApp.Models.BankDetail", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.Cloth", b =>
                {
                    b.HasOne("CustomerShoppingApp.Models.Item", null)
                        .WithOne("cloth")
                        .HasForeignKey("CustomerShoppingApp.Models.Cloth", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.Furniture", b =>
                {
                    b.HasOne("CustomerShoppingApp.Models.Item", null)
                        .WithOne("furniture")
                        .HasForeignKey("CustomerShoppingApp.Models.Furniture", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.Garden", b =>
                {
                    b.HasOne("CustomerShoppingApp.Models.Item", null)
                        .WithOne("garden")
                        .HasForeignKey("CustomerShoppingApp.Models.Garden", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.Item", b =>
                {
                    b.HasOne("CustomerShoppingApp.Models.ShoppingCart", null)
                        .WithOne("item")
                        .HasForeignKey("CustomerShoppingApp.Models.Item", "ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.Shoe", b =>
                {
                    b.HasOne("CustomerShoppingApp.Models.Item", null)
                        .WithOne("shoe")
                        .HasForeignKey("CustomerShoppingApp.Models.Shoe", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.ShoppingCart", b =>
                {
                    b.HasOne("CustomerShoppingApp.Models.Customer", null)
                        .WithOne("shoppingCart")
                        .HasForeignKey("CustomerShoppingApp.Models.ShoppingCart", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.Customer", b =>
                {
                    b.Navigation("address")
                        .IsRequired();

                    b.Navigation("bankDetail")
                        .IsRequired();

                    b.Navigation("shoppingCart")
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.Item", b =>
                {
                    b.Navigation("cloth")
                        .IsRequired();

                    b.Navigation("furniture")
                        .IsRequired();

                    b.Navigation("garden")
                        .IsRequired();

                    b.Navigation("shoe")
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerShoppingApp.Models.ShoppingCart", b =>
                {
                    b.Navigation("item")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
